build:
  image: marcelhuberfoo/pandoc
  script:
    - pandoc text/*.md -o saferscience.pdf --filter pandoc-citeproc pandoc-config.yml
    - pandoc text/*.md -o saferscience.html --filter pandoc-citeproc pandoc-config.yml
  artifacts:
    paths:
      - "*.pdf"
      - "*.html"
  only:
    refs:
      - branches
    changes:
      - text/*
