build:
  image: marcelhuberfoo/pandoc
  script:
    - pandoc text/*.md -o saferscience.pdf --filter pandoc-citeproc pandoc-config.yml
    - pandoc text/*.md -o saferscience.md --filter pandoc-citeproc pandoc-config.yml    
  artifacts:
    paths:
      - "*.pdf"
      - "*.md"
  only:
    refs:
      - branches
    changes:
      - text/*

pages:
  images: 2.6
  script:
  - gem install jekyll
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
  only:
    refs:
      - branches
    changes:
      - text/*
