build:
  image: marcelhuberfoo/pandoc
  script:
    - pandoc text/*.md -o saferscience.pdf --filter pandoc-citeproc pandoc-config.yml
    - pandoc text/*.md -o saferscience.md --filter pandoc-citeproc pandoc-config.yml    
  artifacts:
    paths:
      - "*.pdf"
      - "*.md"
  only:
    refs:
      - branches
    changes:
      - text/*