build:
  image: marcelhuberfoo/pandoc
  script:
    - pandoc text/*.md -o saferscience.pdf --filter pandoc-citeproc pandoc-config.yml
    - pandoc text/*.md -o saferscience.md --filter pandoc-citeproc pandoc-config.yml    
  artifacts:
    paths:
      - "*.pdf"
      - "*.md"
  only:
    refs:
      - branches
    changes:
      - text/*

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

pages:  
  
  image: ruby:2.6
  stage: deploy
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    refs:
      - branches
    changes:
      - text/*
